<?php

namespace App\Services;

use Illuminate\Support\Facades\Storage;

class CodeGenerator
{
    /**
     * Create a minimal Next.js repo zip skeleton using project.json.
     * Returns path to zip (storage/app/artifacts/{buildId}.zip)
     */
    public function makeNextRepoZip(string $buildId, array $projectJson): string
    {
        $root = "artifacts/{$buildId}";
        Storage::makeDirectory($root);

        $pkg = [
            "name" => strtolower(preg_replace('/\s+/', '-', $projectJson['meta']['name'] ?? "app-{$buildId}")),
            "version" => "0.1.0",
            "private" => true,
            "scripts" => [
                "dev" => "next dev",
                "build" => "next build",
                "start" => "next start"
            ],
            "dependencies" => [
                "next" => "14.2.0",
                "react" => "18.2.0",
                "react-dom" => "18.2.0"
            ]
        ];

        Storage::put("$root/package.json", json_encode($pkg, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
        Storage::put("$root/README.md", "# Generated by Apploom AI\n\nRun `npm i && npm run dev`.\n");
        Storage::put("$root/next.config.js", "module.exports = { reactStrictMode: true };\n");

        // simple app dir
        Storage::makeDirectory("$root/app");
        Storage::put("$root/app/page.js", $this->reactPage($projectJson));
        Storage::put("$root/app/layout.js", $this->layoutJs($projectJson['meta']['name'] ?? 'App'));

        // write project.json
        Storage::put("$root/project.json", json_encode($projectJson, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));

        // zip
        $zipPath = "artifacts/{$buildId}.zip";
        $this->zipFolder(storage_path("app/$root"), storage_path("app/$zipPath"));

        // cleanup folder (keep zip)
        Storage::deleteDirectory($root);

        return $zipPath;
    }

    private function layoutJs(string $title): string
    {
        return <<<JS
export const metadata = { title: "{$this->e($title)}" };
export default function RootLayout({ children }) {
  return (<html lang="en"><body style={{fontFamily:"system-ui,Segoe UI,Roboto,Arial"}}>{children}</body></html>);
}
JS;
    }

    private function reactPage(array $projectJson): string
    {
        $title = $this->e($projectJson['meta']['name'] ?? 'App');
        $hero  = $this->e($projectJson['pages'][0]['sections'][0]['props']['title'] ?? 'Welcome');
        return <<<JS
export default function Page(){
  return (
    <main style={{padding:"24px"}}>
      <h1 style={{marginBottom:12}}>{$title}</h1>
      <div style={{background:"#f3f5f8", border:"1px solid #dfe5ee", borderRadius:12, padding:16}}>
        <h3>{$hero}</h3>
        <p>This Next.js skeleton was generated by Apploom AI.</p>
      </div>
    </main>
  );
}
JS;
    }

    private function zipFolder(string $srcDir, string $zipFile): void
    {
        $zip = new \ZipArchive();
        if ($zip->open($zipFile, \ZipArchive::CREATE|\ZipArchive::OVERWRITE) !== true) {
            throw new \RuntimeException("Cannot create zip: $zipFile");
        }
        $src = realpath($srcDir);
        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($src, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );
        foreach ($files as $file) {
            $filePath = $file->getRealPath();
            $local = substr($filePath, strlen($src) + 1);
            if ($file->isDir()) $zip->addEmptyDir($local);
            else $zip->addFile($filePath, $local);
        }
        $zip->close();
    }

    private function e(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }
}
